### ISSUE TITLE
ZeroMe blank page

### ISSUE THREAD

**Issue by rllola** [HelloZeroNet/ZeroMe#122]
Hi,

I am trying to access ZeroMe but it is a blank page. In the console I have an error message : 
```
SyntaxError: invalid regexp group
```

There has been a new update recently, could it be the cause ?

**Comment by HelloZeroNet** [comment]
Thanks, fixed! https://github.com/HelloZeroNet/ZeroMe/commit/9301f46d16a74178cc7a18b8e63c5567863594c9

(Didn't knew there is a regexp difference between Chrome and Firefox.)
