### ISSUE TITLE
Coffeescript compile error

### ISSUE THREAD

**Issue by binhgo** [HelloZeroNet/ZeroMe#124]
Compile coffee script error. 

MacOS 10.13.6
ZeroNet 0.6.3
CoffeeScript 1.12.7 or 2.x
Running ZeroNet in debug mode

and getting this error:
![screen shot 2018-09-17 at 10 22 31 am](https://user-images.githubusercontent.com/10021934/45611561-06f87700-ba8a-11e8-8cd3-c452539ba4c1.png)

**Comment by HelloZeroNet** [comment]
I can confirm it does not works with Coffeescript 2.x (probably it would require major changes), but it compiles with 1.12.8.

**Comment by binhgo** [comment]
yes, I found that it wont work with coffee 2.x, so that I install coffee 1.x (1.12.7 and 1.7.0), I tried both, but it does not work.

Both version of coffee 1.x gave me the error above. The site I am using to test it ZeroMe.

1. I create a new zite
2. I clone the ZeroMe from github
3. I open Developer tools to force CoffeeScript complier
4. It gave me the error above

**Comment by HelloZeroNet** [comment]
I'm pretty sure the error message you get is given by coffeescript 2.x.

Please test the version using `coffee --version`

**Comment by binhgo** [comment]
Yup, seem that Coffee 1.x now took affect, After some restarts, now I can build Coffee -> JS.

Thanks 👍 

For other people:
1. install Coffee 1.12.7: npm install -g coffeescript@1.12.7
2. stop all ZeroNet instance and restart the machine, I restarted 3 times and it works
3. Run ZeroNet, open Developer tools in browser and reload the page
