### ISSUE TITLE
"Three dots" menu is too hidden, make it appear always or on mouse hover over the post

### ISSUE THREAD

**Issue by slrslr** [HelloZeroNet/ZeroMe#134]
Hello,

it is too hard to spot three dots menu of the ZeroMe post. It shows for me (Firefox) only when mouse cursor is above the post header.

I can not find any reason why the three dots should not appear always or at least when mouse hover over whole post, not just tiny header. Similar with editting pencil which is hard to spot and show only when mouse is over the post text, not over any part of the post.

Thank you

**Comment by leftside2** [comment]
How about putting '🔧' unicode character in place of 3-dot?

**Comment by slrslr** [comment]
this one ≡
or: https://www.abeautifulsite.net/the-unicode-character-for-menu-icons

**Comment by HelloZeroNet** [comment]
I have made it bigger, darker and always visible. I think it's hard to miss this way.
https://github.com/HelloZeroNet/ZeroMe/commit/b1b84d77736894040a95c86b541369f1df21c830

**Comment by slrslr** [comment]
@HelloZeroNet along with this change i think it makes sense to show the "Edit" menu entry inside the dot menu on zerome posts.
(Currently not experienced user can miss the hard to spot editing pencil icon and if there is post menu, it makes sense to contain "Edit" entry)

**Comment by slrslr** [comment]
@HelloZeroNet another issue is described [here](/1MeFqFfFFGQfa1J3gJyYYUvb5Lksczq7nH/?Post/1oranGeS2xsKZ4jVsu9SVttzgkYXu4k9v/16NS3rBdW9zpLmLSQoD8nLTtNVsRFtVBhd/1566849283) (please kindly check/reopen this issue)

Thank you

**Comment by HelloZeroNet** [comment]
I just added both things: https://github.com/HelloZeroNet/ZeroMe/commit/6c8ac2f81f30408fa6389a50b63ef22adaa485c3 https://github.com/HelloZeroNet/ZeroMe/commit/6c8ac2f81f30408fa6389a50b63ef22adaa485c3
