### ISSUE TITLE
Editing the profile info glitches

### ISSUE THREAD

**Issue by geekless** [HelloZeroNet/ZeroMe#142]
It's a bit hard to explain, it's better to attach the video:

http://127.0.0.1:43110/1CiXRY9ATZSoZqBzwMfXEMsKtPRt2aQoF2/data/users/1GooUE19488nDwG3TdkM8seYAHct4gjkq4/zerome-profile-editing-bug.mp4

1. Pressing the edit button, the page scrolls down and the edit box hides behind the window border.

2. Any attempt to clear the edit box (Delete, Ctrl + X, etc) forces the old text content to restore.

**Comment by HelloZeroNet** [comment]
Thanks for reporting, I was able to reproduce and fix the problems: 
https://github.com/HelloZeroNet/ZeroMe/commit/b04a38409bff2dbfcf47daa844bf7ab16b0404dc
https://github.com/HelloZeroNet/ZeroMe/commit/4a462dc9aa2eff648e74b467ae0c3e512d093bf3
