### ISSUE TITLE
IPv6 address links don't work.

### ISSUE THREAD

**Issue by styromaniac** [HelloZeroNet/ZeroMe#147]
On ZeroTalk, they do, but on ZeroMe, I get in the address bar:

>about:blank#blocked

![Screenshot_20200923-192926](https://user-images.githubusercontent.com/43807387/94084400-686b2300-fdd3-11ea-8cb2-8fb5ccd6c7e6.png)

It doesn't even become clickable until I use square brackets and parenthesis to title the link.

It doesn't matter if App 0 is in use. It's the same in plain Chrome. Firefox doesn't do anything when clicking the blue link.

Arching Kaos Radio (example IPv6 address link)
https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f]/

**Comment by HelloZeroNet** [comment]
Looks like [markedjs](https://github.com/markedjs/marked) does not recognize ipv6 addresses:

```
> marked("http://any.txt https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f] sasdw wewe")
"<p><a href="http://any.txt">http://any.txt</a> https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f] sasdw wewe</p>"
```

**Comment by HelloZeroNet** [comment]
Opened an issue for it: https://github.com/markedjs/marked/issues/1763

**Comment by styromaniac** [comment]
Why ZeroTalk has no problem is my question.

**Comment by HelloZeroNet** [comment]
Looks like an earlier version of marked does turn ipv6 urls to links:

ZeroTalk (Marked 2014 version):

```js
> marked("IPv4 url: http://127.0.0.1/index.html\n IPv6 url: https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f]/\n")
< "<p>IPv4 url: <a href="http://127.0.0.1/index.html">http://127.0.0.1/index.html</a>
 IPv6 url: <a href="https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f]/">https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f]/</a></p>
"
```

ZeroMe (Marked 2018 version):

```js
> marked("IPv4 url: http://127.0.0.1/index.html\n IPv6 url: https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f]/\n")
< "<p>IPv4 url: <a href="http://127.0.0.1/index.html">http://127.0.0.1/index.html</a>
 IPv6 url: https://[205:2c4b:693e:44fb:635f:9dae:510:aa1f]/</p>
"
```

So we can try to revert to previous version, or replace these links with a regexp.

**Comment by styromaniac** [comment]
I've switched to ZeroTalk's version.

**Comment by styromaniac** [comment]
With Marked 2014 version, I can't use square brackets around an IPv6 link to title it.

`[Test](http://[::1]:12345/)`

**Comment by styromaniac** [comment]
I say we should go with the Marked 2014 version.

But I must ask: What are the pros and cons of a regexp?

**Comment by HelloZeroNet** [comment]
It should be fixed by https://github.com/HelloZeroNet/ZeroMe/commit/dd2719c63731a0c1e648bcc2d9a9d81e7326baaa

> But I must ask: What are the pros and cons of a regexp?

Later version of the marked.js lib could have bug fixes/new features (like links between < and >)
