### ISSUE TITLE
Unable to edit/delete comments

### ISSUE THREAD

**Issue by Emeraude** [HelloZeroNet/ZeroMe#2]
I can't edit nor delete comments I posted on someone else posts.
When I try to edit, I get this error in the developer console:
```
TypeError: data.comment[comment_index] is undefined in all.js:3703:11
```
When I try to delete, eveything looks fine, I got the `Are you sure?` prompt and then the message `Content published to X peers.` But actually, nothing is deleted.

I do not encounter this issue when I try to edit or delete comments on my one posts, that works well.

I'm using firefox 48.0 on an up to date archlinux.

**Comment by HelloZeroNet** [comment]
I have just tried and I was unable to reproduce it: it's working for me in Chrome and FF also, so probably it's something else

**Comment by Emeraude** [comment]
I get a different error on chromium:
```
all.js:3752 Uncaught TypeError: Cannot set property 'body' of undefined
```

**Comment by HelloZeroNet** [comment]
I think its fixed now (happened when you commented on different hub)

**Comment by Emeraude** [comment]
It seems to be fixed now.
Thanks.
