### ISSUE TITLE
The results of "Search in users..." is displayed under "New users in ZeroMe"

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroMe#20]
/Me.ZeroNetwork.bit/?Users
![search](https://cloud.githubusercontent.com/assets/18724949/20741056/c13f9fea-b702-11e6-858d-804306ffd835.png)
By the way, "Search in users..." "Most active" should be translated.

**Comment by HelloZeroNet** [comment]
Thanks, fixed!
