### ISSUE TITLE
Can't load more comments if there is too many comments

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroMe#28]
Access this post: http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/1RedkCkVaXuVXrqCMpoXQS29bwaqsuFdL/13Z7XxTa7JuFat3KzzMWu3onwM6biLuurJ/1483720921
If you click "Show more comments...", there is no response.

But if you access his profile page: http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Profile/1RedkCkVaXuVXrqCMpoXQS29bwaqsuFdL/13Z7XxTa7JuFat3KzzMWu3onwM6biLuurJ/p2p@zeroid.bit
and click "Show more comments...", comments will be load successfully.

**Comment by HelloZeroNet** [comment]
Thanks, fixed!
