### ISSUE TITLE
Feature: searching for users by @zero.bit ID

### ISSUE THREAD

**Issue by crypdick** [HelloZeroNet/ZeroMe#29]
It would make it a lot easier to find folks!

**Comment by stijnkliemesch** [comment]
Yes, right now it's only possible to search by the name entered on the user card profile. As this can be edited on a whim, being able to search for an account by an identifier with more permanence seems to me a desirable feature.

**Comment by HelloZeroNet** [comment]
I have added this feature: https://github.com/HelloZeroNet/ZeroMe/commit/52c9bfff0f2d767f56a72bfb9fd487bad9232607
