### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by cryptid11** [HelloZeroNet/ZeroMe#36]
To gat names of users? Followers and followed for user? Or can you give me any hint to craft one?

**Comment by HelloZeroNet** [comment]
You can query the database itself (standard sqlite3 format): data/1MeFqFfFFGQfa1J3gJyYYUvb5Lksczq7nH/merged-ZeroMe/ZeroMe.db
For all users: `SELECT * FROM user`, 
Followed users: `SELECT * FROM follow LEFT JOIN json USING (json_id) WHERE json.cert_user_id = "nofish@zeroid.bit"`
Followers: `SELECT * FROM follow LEFT JOIN json USING (json_id) WHERE follow.user_name = "Nofish"`

**Comment by cryptid11** [comment]
Thanks a lot!

**Comment by cryptid11** [comment]
Sorry why this doesn't work?
http://pastebin.com/VKYbPgZW It seems cert_user_id it's always None and my workaround doesn't works, I can't understand why.
