### ISSUE TITLE
User Profile Creation Bug?

### ISSUE THREAD

**Issue by undiagnosed** [HelloZeroNet/ZeroMe#41]
When a new user profile is created on ZeroMe, the following happens:

1UDbADib99KE9d3qZ87NqJF2QLTHmMkoV/data/userdb/<user_hash>/content.json is created with the following content:

{
 "user": [
  {
   "date_added": 1489271191,
   "avatar": "generate",
   "hub": "1oranGeS2xsKZ4jVsu9SVttzgkYXu4k9v",
   "intro": "Random ZeroNet user",
   "user_name": "Zerometst"
   }
  ]
}

Then the file is signed and the previous information that was written is overwritten with the signing data and the user data is no longer in the file. The relevant code is in User.coffee in the saveUserdb function at lines 144-145 where fileWrite and sitePublish commands are called. 

Also, no entry is added to the database user table (not sure if it's supposed to be). Entries are added to the json table. However, in my site which is based off of ZeroMe, no entries are added to either table in the database. Where do the writes to the database file occur?

**Comment by HelloZeroNet** [comment]
Thanks, looks like it got broken somewhere.
Fixed in latest release:
https://github.com/HelloZeroNet/ZeroNet/commit/2473a09f7b45b0d1d331c52c1ae91441188fbbdf
And also added a test for it:
https://github.com/HelloZeroNet/ZeroNet/commit/f46f9fa6ea5d1e867a4865b8eaddb92fb96d6082
