### ISSUE TITLE
Linked Post shows two posts

### ISSUE THREAD

**Issue by anoadragon453** [HelloZeroNet/ZeroMe#7]
This links shows two instances of the same post with different sets of comments, one older and one more up to date. I'm not sure if I'm the only one with this issue, perhaps my database has two copies of the same post?

Here is the link:

http://127.0.0.1:43110/Me.ZeroNetwork.bit/?Post/1RedkCkVaXuVXrqCMpoXQS29bwaqsuFdL/14J8mC3K7k5Ygx22uu9LUzGWnBoDAQdyDo/3

**Comment by Plasmmer** [comment]
@mkg20001, its fixed?

**Comment by anoadragon453** [comment]
@Plasmmer Oops, yes this has been long fixed. It was due to an issue with joining two ZeroMe instances.
