### ISSUE TITLE
Feature request: permalinks to comments

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroMe#71]

**Comment by mkg20001** [comment]
![image](https://cloud.githubusercontent.com/assets/7735145/24581476/5448e886-171c-11e7-9ea6-408aa88059cd.png)
This feature already exists

**Comment by Plasmmer** [comment]
But when I rightclick the comment date, I can't get his link.
<img src="http://image.prntscr.com/image/574eb45ebbfe4685be1c20c16f7f0a6c.png"/>

**Comment by mkg20001** [comment]
You have to hover over the post header then that tree dot thing appears 
![image](https://cloud.githubusercontent.com/assets/7735145/24581546/dcb73bf4-171d-11e7-8c50-5830c183816d.png)

When you left-click on that a menu shows up

(But yes that's a bit un-intuitive)

**Comment by Plasmmer** [comment]
I'm talking about comments, not the posts.

**Comment by Plasmmer** [comment]
Already in: https://github.com/mkg20001/ZeroMe/issues/8.
