### ISSUE TITLE
Feature request: Groups

### ISSUE THREAD

**Issue by Plasmmer** [HelloZeroNet/ZeroMe#72]

**Comment by owintwist** [comment]
-1

**Comment by WonderingDane** [comment]
@owintwist Why?

**Comment by owintwist** [comment]
@WonderingDane good question : Why ?

Pros first.

**Comment by Plasmmer** [comment]
The pros are more organized posts and discussions for communities with same or like purposes.

**Comment by owintwist** [comment]
S'il est question de regrouper des personnes qui ont les même centre d'intérêts, alors il est plus pertinent d'utiliser les mots-clés plutôt que les groupes. Car une fois que vous êtes dans un groupe, vous êtes _enfermés_ dans ce groupe. En utilisant les tags, on fait de nouvelles découvertes par le hasard des recherches.

Je suis fatigué de ces réseaux qui cherchent à nous dire ce qu'il faut voir. À la fin, il y a des _influenceurs_ qui captent mécaniquement toute l'attention et laissent les _petits_ se vautrer. Non, il faut qu'on soit tous égaux sur un réseau social, garder la curiosité éveillée et le meilleur moyen pour ça, c'est une seule timeline, tout le monde dessus, pas de discrimination et un système d'abonnement mono-directionnel.

Oui, ça fait très Twitter. Mais je préfère que ZeroMe soit plus proche d'un _Twitter-like_ que d'un _Facebook-like_ ou d'un _Google+like_ qui ont tellement de fonctions inutiles au point d'en devenir des gouffres à ressources système !

Enfin, petite mise au point : @Plasmmer a des idées intéressantes et d'autres non, et quand c'est le cas, j'exprime mon point de vue. Si vous avez du mal avec ça, faudra vous y faire : je considère que si quelqu'un a le droit de dire simplement "je veux ça", j'ai très bien le droit de répondre "j'en veux pas", tout aussi peu argumenté. Merci de calmer vos agressions.

**Comment by Plasmmer** [comment]
Already in: https://github.com/mkg20001/ZeroMe/issues/50.
