### ISSUE TITLE
The translation of "Hide \"Hello ZeroMe!\" messages" doesn't effect

### ISSUE THREAD

**Issue by l5h5t7** [HelloZeroNet/ZeroMe#81]
Can't replace "Hide \"Hello ZeroMe!\" messages" because "Hello ZeroMe!" is replaced.

**Comment by ysc3839** [comment]
Try moving this item to top.

**Comment by l5h5t7** [comment]
I tried it, but it's useless. I have found the reason.

**Comment by l5h5t7** [comment]
#82
