### ISSUE TITLE
Switch profile (hub)

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroMe#85]
Further of #11

1. click my ID, popup a switcher
2. click my nickname, just jump to my current profile

I expect a profile indicator and switcher like ①

> ![image](https://user-images.githubusercontent.com/15178410/28261440-e4b94cf0-6b11-11e7-890f-2c66cebde689.png)

**Comment by 0polar** [comment]
https://github.com/HelloZeroNet/ZeroMe/commit/614851064efec30d418d161c14b9fe9dbb429764
