### ISSUE TITLE
Feature: Personal Block List

### ISSUE THREAD

**Issue by mattmacpherson** [HelloZeroNet/ZeroMe#9]
As ZeroMe grows in popularity, it will inevitably get polluted with spam, trolling and lunacy. A personal block list + a block list users can subscribe to may be one possible solution.

**Comment by MoreJ** [comment]
Might be better to introduce the feature to ZeroNet as a whole: block posts/content from people on your personal block list. That way you won't see their comments/posts/submissions/etc. on any site.

**Comment by deavmi** [comment]
I agree with @MoreJ

**Comment by cxgreat2014** [comment]
I agree with @MoreJ

**Comment by Ernest-su** [comment]
I agree with @MoreJ

**Comment by ogxgo** [comment]
I agree with @MoreJ

**Comment by rainlime** [comment]
I agree with @MoreJ

**Comment by cxgreat2014** [comment]
I agree with @rainlime

**Comment by slrslr** [comment]
I think this requested feature was added by @nofish
