### ISSUE TITLE
When nickname is empty, the page is "not found"

### ISSUE THREAD

**Issue by zcyzcy88** [HelloZeroNet/ZeroMe#92]
I carelessly clear my nickname, then I can't add it back.

<img width="833" alt="2017-07-22 18_36_02-zerome - zeronet" src="https://user-images.githubusercontent.com/15178410/28490457-18cd564a-6f0d-11e7-878b-870df947524f.png">

**Comment by HelloZeroNet** [comment]
Thanks for reporting, fixed: https://github.com/HelloZeroNet/ZeroMe/commit/3382ca06ca6eb6be038e18994bc66959eeb6f23f
