### ISSUE TITLE
Zero Menu covers too much on mobile phone

### ISSUE THREAD

**Issue by sczhg** [HelloZeroNet/ZeroMe#95]
On my iPhone, after dragging "0" menu to left, the menu covers too much and i can't leave except refresh. 
Maybe this menu can be more responsive to device screen width? Or a "close" button should be offered? Thx.

This is what it looks like.

![wechat image_20170729150338](https://user-images.githubusercontent.com/3379379/28742930-249e034a-746f-11e7-86b1-e6ffc14aff2c.jpg)

**Comment by HelloZeroNet** [comment]
Thanks for reporting, i have added a close button in Rev2169 (https://github.com/HelloZeroNet/ZeroNet/commit/527c2b4f54a14849d39f768494432ef2d50ceac4) and also reduced the scale of ZeroMe to 0.8 from 0.1 to make it fit on smaller screens
